# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Wiggle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Wiggle
  pod 'Parse'
  pod 'Parse/FacebookUtils'
  pod 'FacebookLogin'
  pod 'FacebookCore'
  pod 'FacebookShare'
  pod 'RLBAlertsPickers', '~> 1.1.1'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'
  pod 'Hero'
  pod 'NVActivityIndicatorView'
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod 'MessageKit'
  pod 'PromiseKit'
  pod 'Koloda', :git => 'https://github.com/Yalantis/Koloda.git'
  pod 'PopupDialog'
  pod 'ParseLiveQuery'
  pod 'SwiftMessages'
  pod 'SwiftyStoreKit'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Alamofire'
  pod "ImageSlideshow/Kingfisher"
end

post_install do |installer|
installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
end

installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
end
end
