# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Wiggle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wiggle
  pod 'Parse'
  pod 'Parse/FacebookUtils'
  pod 'FacebookLogin'
  pod 'FacebookCore'
  pod 'FacebookShare'
  pod 'RLBAlertsPickers', '~> 1.1.1'

end
